name: Angular 17 - CI/CD com Verificação de Sintaxe

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Atualize para a versão mais recente

      - name: Instalar Node.js
        uses: actions/setup-node@v3  # Atualize para a versão mais recente
        with:
          node-version: 20  # Use a versão 20 do Node.js

      - name: Instalar dependências
        run: npm install

      - name: Verificação de sintaxe
        run: npm run lint

      - name: Exibir erros de sintaxe
        if: ${{ failure() }}
        run: echo "Erros de sintaxe encontrados!"

